CREATE TABLE suicides (
    id TEXT PRIMARY KEY,
    UNIT TEXT,  
    UNIT_NUM INT,
    INDICATOR TEXT,
    STUB_NAME TEXT, 
    STUB_NAME_NUM INT,
    STUB_LABEL TEXT,
    STUB_LABEL_NUM INT,
    YEAR INT NOT NULL,
    AGE TEXT,  
    AGE_NUM INT,  
    ESTIMATE FLOAT NOT NULL,
    FLAG TEXT  
);
